module.exports = {
    apps: [
        {
            name: 'Katpool_App',
            script: 'bun run index.ts',
            instances: 1,
            exec_mode: 'fork',
            watch: false,
            autorestart: true,
            source_map_support: true,
        },
        {
            name: 'Go_Fetch_Template',
            cwd: './go/',
            script: './getNewBlockTemplate',
            instances: 1,
            exec_mode: 'fork',
            watch: false,
            autorestart: true,
            source_map_support: true,
        },
        {
            name: 'Katpool_Monitor',
            cwd: '../katpool-monitor-mainnet/',
            script: 'bun run src/index.ts',
            instances: 1,
            exec_mode: 'fork',
            watch: false,
            autorestart: true,
            source_map_support: true,
        },
        {
            name: 'Katpool_Payment',
            cwd: '../katpool-payment-mainnet/',
            script: 'bun run src/index.ts',
            instances: 1,
            exec_mode: 'fork',
            watch: false,
            autorestart: true,
            source_map_support: true,
        },
    ],
};